<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Active' => 'Aktív',
    'Are you sure' => 'Biztos',
    'Are you sure you want to delete this item?' => 'Biztos törlöd ezt az elemet?',
    'Close' => 'Bezár',
    'Create' => 'Létrehozás',
    'Create Text' => 'Szöveg létrehozása',
    'Creation time' => 'Létrehozás időpontja',
    'Creation user' => 'Létrehozó felhasználó',
    'Delete' => 'Törlés',
    'Deleted' => 'Törölt',
    'Error' => 'Hiba',
    'Id' => 'Id',
    'Inactive' => 'Inkatív',
    'Modification time' => 'Módosítás időpontja',
    'Modification user' => 'Módosító felhasználó',
    'No' => 'Nem',
    'Reset' => 'Visszaállítás',
    'Search' => 'Keresés',
    'Slug' => 'Slug',
    'Something went wrong, please try again later!' => 'Sajnos hiba történt kérek próbáld meg később!',
    'Status' => 'Státusz',
    'Text' => 'Szöveg',
    'Texts' => 'Szövegek',
    'Title' => 'Megnevezés',
    'To delete {title} text?' => 'törlöd a(z) {title} szöveget?',
    'Update' => 'Módosítás',
    'Update {modelClass}: ' => '{modelClass} módosítása',
    'View Text' => 'Szöveg megtekintése',
    'Yes' => 'Igen',
];
